config/routes.rb
Rails.application.routes.draw do
  resources :pages
  resources :members, path: 'firmantes'
  devise_for :users, path: ''
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get 'firmas', to: 'homepage#signatures', as: 'signatures'
  root 'members#new'

  get 'admin', to: redirect('/sign_in')
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/member.rb
class Member < ApplicationRecord
  
  validates :name, presence: true, length: { minimum: 3 }
  validates :email, format: Devise::email_regexp, allow_blank: true
  validates :rut, rut: { message: "no es un RUT válido" }, presence: true, uniqueness: true
  rescue_from_duplicate :rut
  rescue_from_duplicate :email

  scope :by_creation_date, -> { order(created_at: :desc) }
  scope :by_name,  -> {order(name: :asc)}

  def rut=(value)
    value = value.gsub('.','')
    write_attribute(:rut, value)
  end

  def self.to_csv(options = {})
	CSV.generate(options) do |csv|
		csv << column_names
			all.each do |member|
				csv << member.attributes.values_at(*column_names)
			end
		end
	end

end

app/models/page.rb
class Page < ApplicationRecord
	validates :body, presence: true
	validates :tag, presence: true, uniqueness: true
	validates :title, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception, prepend: true

  helper_method :admin?
  def admin?
    current_user.try(:admin)
  end

  def authorize
    unless admin?
      #render status: 401
      redirect_to root_url
    end
  end

end

app/controllers/homepage_controller.rb
class HomepageController < ApplicationController
  

  def signatures
    @members = Member.by_creation_date
  end
end

app/controllers/members_controller.rb
class MembersController < ApplicationController
  before_action :set_member, only: [:show, :edit, :update, :destroy]
  before_action :authorize, except: [:new, :create]

  # GET /members
  # GET /members.json
  def index
    @members = Member.all.by_name
    respond_to do |format|
      format.html
      format.csv { send_data @members.to_csv }
    end
  end

  # GET /members/1
  # GET /members/1.json
  def show
  end

  # GET /members/new
  def new
    @member = Member.new
  end

  # GET /members/1/edit
  def edit
  end

  # POST /members
  # POST /members.json
  def create
    @member = Member.new(member_params)

    respond_to do |format|
      if @member.save
        format.html { redirect_to root_url, notice: 'Muchas gracias por unirte. ¡Ahora comparte en tus redes!' }
        format.json { render :show, status: :created, location: @member }
      else
        format.html { render :new }
        format.json { render json: @member.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /members/1
  # PATCH/PUT /members/1.json
  def update
    respond_to do |format|
      if @member.update(member_params)
        format.html { redirect_to members_path, notice: 'Firma fue actualizada.' }
        format.json { render :show, status: :ok, location: @member }
      else
        format.html { render :edit }
        format.json { render json: @member.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /members/1
  # DELETE /members/1.json
  def destroy
    @member.destroy
    respond_to do |format|
      format.html { redirect_to members_url, notice: 'Firma fue borrada exitosamente.' }
      format.json { head :no_content }
    end
  end
  helper_method :page
  def page
    @page ||= Page.find_by(tag: 'main')
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_member
      @member = Member.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def member_params
      params.require(:member).permit(:name, :email, :rut)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  before_action :set_page, only: [:show, :edit, :update, :destroy]
  before_action :authorize

  # GET /pages
  # GET /pages.json
  def index
    @pages = Page.all
  end

  # GET /pages/1
  # GET /pages/1.json
  def show
  end

  # GET /pages/new
  def new
    @page = Page.new
  end

  # GET /pages/1/edit
  def edit
  end

  # POST /pages
  # POST /pages.json
  def create
    @page = Page.new(page_params)

    respond_to do |format|
      if @page.save
        format.html { redirect_to pages_url, notice: 'Declaración fue guardada exitosamente.' }
        format.json { render :show, status: :created, location: @page }
      else
        format.html { render :new }
        format.json { render json: @page.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pages/1
  # PATCH/PUT /pages/1.json
  def update
    respond_to do |format|
      if @page.update(page_params)
        format.html { redirect_to pages_url, notice: 'Declaración fue guardada exitosamente updated.' }
        format.json { render :show, status: :ok, location: @page }
      else
        format.html { render :edit }
        format.json { render json: @page.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pages/1
  # DELETE /pages/1.json
  def destroy
    @page.destroy
    respond_to do |format|
      format.html { redirect_to pages_url, notice: 'Declaración fue borrada exitosamente.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_page
      @page = Page.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def page_params
      params.require(:page).permit(:title, :body, :tag)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def markdown(text)
	 Redcarpet::Markdown.new(Redcarpet::Render::HTML, autolink: true, tables: true).render(text).html_safe
  end
end

app/helpers/members_helper.rb
module MembersHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/homepage/signatures.html.erb
<%= link_to 'Ver declaración', root_url, class: 'btn btn-secondary' %>
<%= link_to 'Firma tú también!', root_url + '#firma', class: 'btn btn-primary' %>
<br>
<br>
<h1>Firmas</h1>

<ol id="signatures">
  <% @members.each do |member| %>
      <li><%= member.name %></li>
  <% end %>
</ol>

<%= link_to 'Ver declaración', root_url, class: 'btn btn-secondary' %>
<%= link_to 'Firma tú también!', root_url + '#firma', class: 'btn btn-primary' %>

app/views/layouts/_analytics.html.erb
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-79080600-1', 'auto');
  ga('send', 'pageview');

</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="es">
  <head>
    <title>Prioridad Infancia</title>
    <%= csrf_meta_tags %>
    <% if admin? %>
      <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <% end %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <link href='https://fonts.googleapis.com/css?family=Lora:400,400italic,700,700italic' rel='stylesheet' type='text/css'>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <%= render 'layouts/analytics' %>
  </head>

  <body>
    
    <nav class="navbar navbar-fixed-top navbar-light bg-faded">

      <% if admin? %>
        <nav class="navbar navbar-dark bg-inverse" id="admin-navbar">
          <h3 class="pull-xs-left">Administración</h3>
          <ul class="nav navbar-nav pull-xs-right">
            <li class="nav-item">
               <%= link_to 'Declaración', pages_path, class: 'nav-link' %>
            </li>
            <li class="nav-item">
               <%= link_to 'Firmas', members_path, class: 'nav-link' %>
            </li>  

            <li class="nav-item">
               <%= link_to 'Logout', destroy_user_session_path, method: :delete, class: 'nav-link' %> 
            </li>  
          </ul>
          
        </nav>
      <% end %>
      <ul class="nav navbar-nav">
        <%= link_to 'Prioridad Infancia', root_url, class: 'navbar-brand' %>
        <li class="nav-item">
           <%= link_to 'Declaración', root_url, class: 'nav-link' %>
        </li>
        <li class="nav-item">
           <%= link_to 'Firmas', signatures_path, class: 'nav-link' %>
        </li>   


      </ul>
      <ul class="nav navbar-nav">
        <li class="nav-item pull-xs-right tw">
          <a class="nav-link tw" target="_blank" href="https://twitter.com/intent/tweet?hashtags=NoMásAbusoALaInfancia&text=Súmate en&url=http://prioridadinfancia.cl">
          <i class="fa fa-twitter tw" aria-hidden="true"></i>
          <span class="hidden-xs-down tw">Twittea</span>
          </a>
        </li>  
        <li class="nav-item pull-xs-right right-item fb">
          <a class="nav-link fb" target="_blank" href="https://www.facebook.com/sharer/sharer.php?u=http%3A//prioridadinfancia.cl">
          <i class="fa fa-facebook fb" aria-hidden="true"></i>
          <span class="hidden-xs-down fb">Comparte</span>
          </a>
        </li>
      </ul>
    </nav>

    <div class="container">
      <% if notice %>
        <div class="row">
          <div class="col-md-9">
            <p id="notice" class="alert alert-info" role="alert"><%= notice %></p>
          </div>
        </div>
      <% end %>

      <div class="row">
         <%= yield %>
      </div>

    </div>

    
  </body>
</html>

app/views/members/_form.html.erb
<h3>Únete</h3>
<%= form_for(member) do |f| %>
  <% if member.errors.any? %>
    <div id="error_explanation">
      <h4><%= pluralize(member.errors.count, "error") %>:</h4>

      <ul>
      <% member.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.text_field :name, class: "form-control", placeholder: 'Nombre', pattern: ".{3,}", required: true %>
  </div>

  <div class="form-group">
    <%= f.text_field :rut, class: "form-control", placeholder: 'RUT (ej. 12.345.678-1)', required: true %>
  </div>

  <div class="form-group">
    <%= f.text_field :email, class: "form-control", placeholder: 'Email (opcional)' %>
    <small class="text-muted">Sólo tu nombre será público.</small>
  </div>

  

  <div class="actions">
    <%= f.submit 'Adherir', class: 'btn btn-primary form-control' %>
  </div>
<% end %>

app/views/members/edit.html.erb
<h1>Editing Member</h1>

<%= render 'form', member: @member %>

<%= link_to 'Back', members_path %>

app/views/members/index.html.erb
<h1>Administración de firmas</h1>

<%= link_to "Download CSV", members_path(format: "csv") %>

<table class="table members">
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Email</th>
      <th>Rut</th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% @members.each do |member| %>
      <tr>
        <td><%= member.name %></td>
        <td><%= member.email %></td>
        <td><%= member.rut %></td>
        <td><%= link_to 'Editar', edit_member_path(member), class: "btn btn-sm btn-info" %></td>
        <td><%= link_to 'Borrar', member, method: :delete, data: { confirm: 'Estás seguro?' }, class: "btn btn-sm btn-danger"%></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/members/new.html.erb
<div class="col-md-9">
  <h1><%= page.title %></h1>
  <%= markdown(page.body) %>
  <%= link_to "Junto a otros #{Member.all.count} adherentes", signatures_path %> 
</div>

<div class="col-md-3 col-md-offset-1 sidebar">
  <div class="sidebar-module sidebar-module-inset" id="firma">
    <%= render 'form', member: @member %>
  </div>
 
</div>

app/views/pages/_form.html.erb
<%= form_for(page) do |f| %>
  <% if page.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(page.errors.count, "error") %> prohibited this page from being saved:</h2>

      <ul>
      <% page.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label 'Título' %>
    <%= f.text_field :title, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label 'Cuerpo' %>
    <%= f.text_area :body, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :tag %>
    <%= f.text_field :tag, class: "form-control" %>
  </div>

  <div class="actions">
    <%= f.submit 'Guardar', class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/pages/edit.html.erb
<h1>Modificando Declaración</h1>

<%= render 'form', page: @page %>

app/views/pages/index.html.erb
<table class="table">

  <tbody>
    <% @pages.each do |page| %>
      <tr>
        <td>
          <h1><%= page.title %></h1>
          <%= markdown(page.body) %>
          <br>
        <%= link_to 'Editar', edit_page_path(page), class: 'btn btn-primary' %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/pages/new.html.erb
<h1>New Page</h1>

<%= render 'form', page: @page %>

<%= link_to 'Back', pages_path %>